basic:
    name: 'otsuka-us (news)'
    environments:
        production: 'https://www.otsuka-us.com/'
        staging: 'https://otsukacorp67116main.prod.oapi.com/'
        development: ''
    breakpoints:
        - 375
        - 1440
    pages:
        - discover/2nd-national-forum-on-mental-health-policy
        - discover/akebia-and-otsuka-expand-relationship
        - discover/articles-1000
        - discover/articles-1023
        - discover/articles-1029
        - discover/articles-1032
        - discover/articles-1033
        - discover/articles-1063
        - discover/articles-1069
        - discover/articles-1075
        - discover/articles-1080
        - discover/articles-1083
        - discover/articles-1085
        - discover/articles-1086
        - discover/articles-1087
        - discover/articles-1150
        - discover/articles-1156
        - discover/articles-1174
        - discover/articles-1188
        - discover/articles-1206
        - discover/articles-1208
        - discover/articles-961
        - discover/articles-985
        - discover/compass-series-b
        - discover/data-demonstrate-safety-and-efficacy-in-patients-with-schizophrenia
        - discover/ebony-magazine-bob-oliver-to-2016-power-100
        - discover/fda-accepts-first-digital-medicine-new-drug-application-for-otsuka-and-proteus-digital-health
        - discover/fda-accepts-for-review-otsuka-lundbecks-snda-filing-for-labeling-update-of-rexulti-for-maintenance-treatment-of-schizophrenia
        - discover/fda-accepts-for-review-snda-to-expand-abilify-maintena-labeling
        - discover/fda-accepts-for-review-supplemental-nda-for-deltoid-administration-of-abilify-maintena-extended-release-injectable-suspension
        - discover/fda-approves-deltoid-injection-site-for-abilify-maintena-for-extended-release-injectable-suspension-in-the-treatment-of-schizophrenia
        - discover/fda-approves-dual-chamber-syringe-for-abilify-maintena-for-the-treatment-of-schizophrenia
        - discover/fda-approves-labeling-update-for-sprycel-to-include-3yr-1st-line-and-5yr-2nd-line-efficacy-in-cml
        - discover/fda-approves-labeling-update-for-sprycel-to-include-5yr-1st-line-and-7yr-2nd-line-efficacy-and-safety-data-in-cml
        - discover/fda-issues-complete-response-letter-for-digital-medicine-new-drug-application
        - discover/light-the-way-installation
        - discover/msrd-enters-collaboration-agreement-with-rugen
        - discover/opdc-hosts-roundtable-on-healthcare-and-technology-with-bonnie-watson-coleman
        - discover/otsuka-and-click-therapeutics-collaborate
        - discover/otsuka-and-patrick-j-kennedy-lead-policy-forum-2018
        - discover/otsuka-and-proteus-announce-expanded-collaboration
        - discover/otsuka-and-the-columbia-university-mailman-school-of-public-health-enter-into-a-global-pharmacovigilance-agreement
        - discover/otsuka-and-verily-form-strategic-alliance
        - discover/otsuka-announces-positive-top-line-results-from-two-phase-3-studies-of-centanafadine
        - discover/otsuka-announces-retirement-of-dr-william-h-carson
        - discover/otsuka-earns-designation-as-a-great-place-to-work
        - discover/otsuka-launches-nephu-dedicated-to-kidney-health
        - discover/otsuka-lundbeck-phase-three-brexpiprazole-trial
        - discover/otsuka-lundbeck-to-present-data-on-brexpiprazole-in-schizophrenia-and-mdd-at-apa-annual-meeting
        - discover/otsuka-provides-eligible-newly-uninsured-patients-with-no-cost-access-to-otsuka-medicines
        - discover/positive-top-line-results-from-global-phase-3-program-of-vadadustat
        - discover/proteus-assets-purchase
        - discover/sozosei-foundation-donations-covid-19
        - discover/sozosei-foundation-supports-mental-health-and-kidney-diseases
        - discover/well-beings-campaign-featuring-ken-burns-documentary-series
        - news/4th-annual-mental-health-policy-forum-convenes-national-policymakers-and-advocates-capitol
        - news/akebia-and-otsuka-announce-fda-acceptance-filing-new-drug-application-vadadustat-treatment
        - news/alzheimers-speech-tracking-technology-wins-first-prize-pitch-competition
        - news/announcement-termination-global-license-agreements-renal-anemia-treatment-akebia-therapeutics
        - news/aripiprazole-once-monthly-injectable-shows-superior-effectiveness-paliperidone-palmitate-once
        - news/avanir-pharmaceuticals-inc-business-will-be-integrated-otsuka-america-pharmaceutical-inc
        - news/barbara-corcoran-announces-collaboration-otsuka-and-lundbeck-raise-awareness-agitation
        - news/caring-mental-health-through-music-compassion-and-hope
        - news/connect-4-mental-healthtm-announces-2016-community-innovation-award-recipients
        - news/donations-humanitarian-support-ukrainian-people-otsuka-holdings-and-otsuka-group-companies
        - news/fda-approves-otsuka-and-lundbecks-abilify-asimtufiir-aripiprazole-first-once-every-two-months
        - news/ibm-and-otsuka-develop-transformative-care-coordination-solution
        - news/idalopirdine-granted-fast-track-designation-us-food-and-drug-administration-fda
        - news/jama-neurology-publishes-complete-results-positive-phase-3-study-rexultir-brexpiprazole
        - news/jama-psychiatry-publishes-results-otsuka-and-lundbecks-phase-3-trial-brexpiprazole-combination
        - news/mcquade-center-strategic-research-and-development-and-mindset-pharma-collaborate-develop
        - news/mcquade-center-strategic-research-and-development-enters-agreement-sentinel-oncology-develop
        - news/mcquade-center-strategic-research-and-development-enters-collaboration-ache-develop-potential
        - news/mcquade-center-strategic-research-and-development-launches-otsuka-digital-pioneer-initiative
        - news/meharry-school-global-health-releases-landmark-report-showing-mental-health-inequities-us-0
        - news/mental-health-america-and-otsuka-collaborate-address-mental-health-inequities-new-jersey
        - news/new-england-journal-medicine-publishes-complete-results-positive-phase-2-trial-sibeprenlimab
        - news/new-report-reveals-us-family-caregivers-perform-equivalent-staggering-8735-billion-worth-labor
        - news/new-study-finds-family-caregivers-would-earn-six-figures-if-paid-salary
        - news/nih-public-private-partnership-advance-early-interventions-schizophrenia
        - news/olympic-gold-medalist-missy-franklin-collaborates-otsuka-raise-awareness-kidney-disease
        - news/otsuka-acquires-rights-hematological-cancer-treatment-dacogenr-decitabine-eisai-us
        - news/otsuka-and-lundbeck-announce-fda-acceptance-and-priority-review-snda-brexpiprazole-treatment
        - news/otsuka-and-lundbeck-announce-fda-acceptance-snda-filing-brexpiprazole-combination-sertraline-0
        - news/otsuka-and-lundbeck-announce-fda-acceptance-supplemental-new-drug-application-receive-priority
        - news/otsuka-and-lundbeck-announce-fda-approval-supplemental-new-drug-application-rexultir
        - news/otsuka-and-lundbeck-announce-us-fda-acceptance-new-drug-application-aripiprazole-2-month-ready
        - news/otsuka-and-lundbeck-announce-us-food-and-drug-administration-fda-approval-supplemental-new
        - news/otsuka-and-lundbeck-issue-statement-us-food-and-drug-administration-fda-advisory-committee
        - news/otsuka-and-lundbeck-present-data-acnp-annual-meeting-long-acting-injectable-aripiprazole
        - news/otsuka-and-lundbeck-present-new-data-analyses-efficacy-rexultir-brexpiprazole-agitation
        - news/otsuka-and-lundbeck-present-new-rexultir-brexpiprazole-post-hoc-efficacy-data-analyses
        - news/otsuka-and-lundbeck-present-results-three-clinical-trials-brexpiprazole-combination-sertraline
        - news/otsuka-and-lundbeck-published-study-results-showing-aripiprazole-2-month-ready-use-long-acting
        - news/otsuka-and-lundbeck-submit-new-drug-application-us-brexpiprazole-treatment-schizophrenia-and
        - news/otsuka-and-lundbeck-submit-snda-fda-review-brexpiprazole-and-sertraline-combination-potential
        - news/otsuka-and-sumitomo-revise-license-agreement
        - news/otsuka-and-sunovion-initiate-clinical-development-ulotaront-adjunctive-treatment-major
        - news/otsuka-and-teva-sign-licensing-agreement-japan-prophylactic-migraine-drug-candidate
        - news/otsuka-and-verily-expand-collaboration-novel-clinical-trials-solutions-accelerate-research
        - news/otsuka-announces-corporate-commitment-value-mind-every-family-caregiver
        - news/otsuka-announces-fda-plans-host-advisory-committee-meeting-discuss-snda-brexpiprazole
        - news/otsuka-announces-interim-data-phase-2bc-trial-indicating-new-investigational-compound-may
        - news/otsuka-announces-phase-3-topline-results-avp-786-treatment-agitation-associated-dementia-due
        - news/otsuka-announces-positive-interim-results-phase-3-trial-sibeprenlimab-treatment-immunoglobulin
        - news/otsuka-awarded-grant-phase-2-trial-combining-novel-anti-tuberculosis-compound-opc-167832
        - news/otsuka-becomes-lead-founding-sponsor-pbs-and-wetas-new-caregiving-documentary
        - news/otsuka-co-host-tech-pitch-competition-dementia-solutions
        - news/otsuka-earns-top-score-2023-disability-equality-index
        - news/otsuka-hosts-dr-nina-vasan-governor-charlie-baker-and-representative-jamie-raskin-third-annual
        - news/otsuka-pharmaceutical-acquire-jnana-therapeutics-inc
        - news/otsuka-pharmaceutical-acquire-mindset-pharma-strengthens-pipeline-area-psychiatric-and
        - news/otsuka-pharmaceutical-and-lundbeck-announce-positive-results-showing-reduced-agitation
        - news/otsuka-pharmaceutical-and-lundbeck-announce-topline-results-two-phase-3-trials-brexpiprazole
        - news/otsuka-pharmaceutical-and-lundbeck-present-positive-data-multiple-phase-3-studies-showing
        - news/otsuka-pharmaceutical-and-lundbeck-present-positive-results-showing-reduced-agitation-patients
        - news/otsuka-pharmaceutical-announces-positive-topline-results-two-pivotal-phase-3-trials
        - news/otsuka-pharmaceutical-development-commercialization-inc-develops-relapse-risk-assessment
        - news/otsuka-pharmaceutical-initiates-phase-3-clinical-trial-tolvaptan-patients-autosomal-dominant
        - news/otsuka-provides-update-sibeprenlimab-investigational-monoclonal-antibody-treatment-iga
        - news/otsuka-recognized-best-place-work-disability-inclusion
        - news/otsuka-recognized-driving-greater-equality-women-workplace-healthcare-businesswomens
        - news/otsuka-releases-inaugural-economic-health-impact-report
        - news/otsuka-reports-topline-outcomes-phase-ii-trial-evaluated-brexpiprazole-treatment-borderline
        - news/otsuka-responds-office-inspector-generals-favorable-opinion-regarding-its-hospital-free-trial
        - news/otsukas-economic-and-health-impact-report-20232024
        - news/otsuka-signs-three-year-collaboration-holmusk-enhance-digital-health-and-data-analytics-global
        - news/otsuka-statement-supporting-us-house-reps-passage-21st-century-cures-mental-health-reform
        - news/otsuka-statement-supporting-us-senate-passage-21st-century-cures-mental-health-reform
        - news/otsuka-terminate-development-avp-786
        - news/otsuka-us-pharmaceutical-affiliates-praise-establishment-mental-health-and-substance-use
        - news/otsuka-works-verily-launch-longitudinal-mental-health-registry-advance-novel-research
        - news/rejoyn-fda-authorized
        - news/results-phase-iii-study-brexpiprazole-adult-patients-schizophrenia-published-american-journal
        - news/satcher-health-leadership-institute-morehouse-school-medicine-releases-first-ever-report
        - news/sibeprenlimab-receives-us-fda-breakthrough-therapy-designation-treatment-immunoglobulin
        - news/sozosei-foundation-aims-set-new-course-decriminalizing-and-treating-mental-illness-america
        - news/sozosei-foundation-awards-grants-decriminalize-mental-illness
        - news/startup-health-raises-31m-novartis-ping-group-chiesi-group-guidewell-and-otsuka
        - news/sumitomo-dainippon-pharma-and-otsuka-announce-worldwide-collaboration-and-license-agreement
        - news/sumitomo-pharma-and-otsuka-announce-topline-results-phase-3-diamond-1-and-diamond-2-clinical
        - news/sunovion-and-otsuka-initiate-clinical-development-ulotaront-treatment-generalized-anxiety
        - news/sunovion-sumitomo-dainippon-pharma-and-otsuka-enter-worldwide-development-and
        - news/treating-patients-smi-requires-objective-data-and-patient-buy
        - news/twitter-feed-community-guidelines
        - news/uc-san-diego-center-microbiome-innovation-cmi-announces-otsuka-pharmaceutical-development
        - news/usagainstalzheimers-launches-revolutionary-alzheimers-disease-patient-and-caregiver-engagement
        - news/us-fda-accepts-otsuka-and-lundbecks-filing-review-brexpiprazole-treatment-schizophrenia-and
        - news/us-fda-approves-labeling-update-rexultir-brexpiprazole-maintenance-treatment-schizophrenia
        - news/us-fda-approves-otsuka-and-lundbecks-rexultir-brexpiprazole-adjunctive-treatment-adults-major
        - news/us-food-and-drug-administration-approves-updated-label-otsukas-breathtekr-ubt-h-pylori-kit
        - news/us-food-and-drug-administrations-cardiovascular-and-renal-drugs-advisory-committee-recommends
        - node/1286
        - node/1291
        - node/1681
        - node/666
        - node/671
        - node/676
        - node/681
        - node/686
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 5
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
